# <b>MA0218: Introduction to Data Science and Artificial Intelligence Mini Project</b>
<i>Predicting match outcome based on specific statistic and aspect</i>

<b> Group Member:</b>
1. Antonius Ivan Rahardja Setiawan ()
2. Askana Mirza Maulana Irfany (U2320433A)
3. Theodore Amadeo Argasetya Atmadja (U2320581F)
4. Timothy Louis Barus (U2320344D)
---

## <b>A. Loading the Data</b>
We will use the dataset provided by Jeff Sackmann, which can be download from <a href="https://github.com/JeffSackmann/tennis_atp" target="_blank">Github</a> since it is an open source platform in internet.   

First, all of the comma-seperated values (csv) files will be concenated into one data frames in order to ease the process. 

Based on the description:
> From the dataset, important features to use:
- `surface`: Each surface will effect the movement of the ball, which may affect the match result
- `tourney_level`: Each tournament has their own prestigious, which give pressure to the player
- `winner_seed` and `loser_seed`: Higher rank player will have higher seed in the bracket
- `winner_hand` and `loser_hand`: Dominant hand used can be effect the characteristics of tennis stroke
- `score`: The result of the match
- `best_of`: Tournament usually use best-of-3, except for master and grand slams
- `minutes`: The duration of match will effect the level of fatigue
- `all of the statistics` : Every statistic will determine the player's ability in a match

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib as plt
import seaborn as sb
sb.set()
import os

import warnings
warnings.filterwarnings("ignore")

In [2]:
# Directory path where our CSV files are located
directory = r'C:\NTU\Semester 3\MA0218\dataset_final_project'

# Create an empty list to store DataFrames
data_frames = []

# Loop through all the files in the directory
for filename in os.listdir(directory):
    if filename.endswith(".csv"):  # Check if the file is a CSV
        file_path = os.path.join(directory, filename)
        df = pd.read_csv(file_path)  # Read the CSV file into a DataFrame
        data_frames.append(df)  # Add the DataFrame to the list

# Concatenate all DataFrames
combined_df = pd.concat(data_frames, ignore_index=True)

# Save the concatenated DataFrame to a new CSV file
output_file = 'combined_file.csv'
combined_df.to_csv(output_file, index=False)

In [3]:
pd.set_option("display.max_columns", None)
df_used = pd.read_csv ("combined_file.csv")
df_used.tail(10)

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
921311,2024-2869,Skopje CH,Clay,32,C,20240520,246,126627,NaN,PR,Johan Nikles,R,170.0,SUI,27.1,200385,2.0,NaN,Dan Added,U,NaN,FRA,25.1,W/O,3,Q1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,965.0,14.0,391.0,122.0
921312,2024-2869,Skopje CH,Clay,32,C,20240520,245,202146,NaN,NaN,Luka Pavlovic,U,NaN,FRA,24.1,108710,NaN,WC,Shendrit Deari,R,NaN,MKD,35.2,6-3 6-4,3,Q1,63.0,4.0,3.0,48.0,29.0,27.0,13.0,10.0,0.0,0.0,1.0,0.0,47.0,25.0,15.0,16.0,9.0,0.0,2.0,517.0,75.0,NaN,NaN
921313,2024-2869,Skopje CH,Clay,32,C,20240520,244,200672,NaN,NaN,Sergey Fomin,R,NaN,UZB,23.2,210178,3.0,NaN,Juan Carlos Prado Angelo,U,NaN,BOL,19.2,6-2 2-6 6-2,3,Q1,119.0,0.0,0.0,65.0,32.0,22.0,17.0,12.0,3.0,7.0,5.0,5.0,91.0,40.0,24.0,23.0,12.0,6.0,12.0,654.0,51.0,448.0,100.0
921314,2024-2869,Skopje CH,Clay,32,C,20240520,243,105589,7.0,NaN,Gerald Melzer,L,188.0,AUT,33.8,110748,NaN,PR,Nikola Milojevic,R,188.0,SRB,28.9,6-1 6-4,3,Q1,72.0,7.0,1.0,47.0,19.0,18.0,18.0,9.0,0.0,0.0,1.0,5.0,47.0,32.0,20.0,8.0,8.0,3.0,6.0,475.0,90.0,1073.0,10.0
921315,2024-2869,Skopje CH,Clay,32,C,20240520,242,207764,NaN,NaN,Ryan Nijboer,U,NaN,NED,24.8,126087,NaN,Alt,George Goldhoff,R,NaN,USA,29.3,6-3 6-2,3,Q1,74.0,4.0,2.0,52.0,35.0,26.0,11.0,8.0,3.0,3.0,5.0,7.0,55.0,28.0,17.0,12.0,9.0,6.0,10.0,428.0,108.0,1705.0,1.0
921316,2024-2869,Skopje CH,Clay,32,C,20240520,241,210053,8.0,NaN,Luka Mikrut,U,NaN,CRO,20.0,103872,NaN,WC,Dimitar Grabuloski,U,NaN,MKD,42.5,6-3 6-4,3,Q1,87.0,4.0,6.0,64.0,31.0,24.0,18.0,10.0,2.0,3.0,2.0,5.0,78.0,43.0,30.0,13.0,9.0,6.0,9.0,511.0,76.0,NaN,NaN
921317,2024-2869,Skopje CH,Clay,32,C,20240520,240,208843,5.0,NaN,Jerome Kym,R,198.0,SUI,21.2,210078,NaN,WC,Berk Bugarikj,U,NaN,MKD,20.8,7-5 6-0,3,Q1,77.0,5.0,0.0,44.0,29.0,25.0,9.0,9.0,1.0,2.0,0.0,3.0,60.0,41.0,21.0,8.0,9.0,2.0,7.0,470.0,92.0,NaN,NaN
921318,2024-2869,Skopje CH,Clay,32,C,20240520,239,207484,12.0,NaN,Neil Oberleitner,R,NaN,AUT,24.7,200574,NaN,Alt,Alexander Donski,R,188.0,CAN,25.8,6-4 6-3,3,Q1,82.0,5.0,5.0,54.0,33.0,27.0,13.0,9.0,2.0,2.0,4.0,6.0,72.0,34.0,26.0,15.0,10.0,3.0,6.0,636.0,53.0,955.0,15.0
921319,2024-2869,Skopje CH,Clay,32,C,20240520,238,144970,6.0,NaN,Constantin Bittoun Kouzmine,L,NaN,FRA,25.3,212200,NaN,WC,Amar Huseinovic,U,NaN,MKD,NaN,6-0 6-1,3,Q1,59.0,0.0,1.0,43.0,32.0,26.0,5.0,7.0,4.0,4.0,2.0,0.0,36.0,22.0,9.0,4.0,6.0,0.0,5.0,487.0,87.0,NaN,NaN
921320,2024-2869,Skopje CH,Clay,32,C,20240520,237,202342,NaN,NaN,Ryan Seggerman,U,NaN,USA,24.7,106254,NaN,Alt,Calum Puttergill,U,NaN,AUS,30.5,7-5 6-0,3,Q1,56.0,10.0,1.0,44.0,28.0,22.0,12.0,9.0,0.0,1.0,0.0,9.0,52.0,28.0,19.0,7.0,9.0,3.0,8.0,555.0,67.0,880.0,20.0

In [4]:
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 921321 entries, 0 to 921320
Data columns (total 49 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          921321 non-null  object
 1   tourney_name        921321 non-null  object
 2   surface             916692 non-null  object
 3   draw_size           920486 non-null  object
 4   tourney_level       921321 non-null  object
 5   tourney_date        921321 non-null  int64
 6   match_num           921321 non-null  int64
 7   winner_id           921321 non-null  int64
 8   winner_seed         390020 non-null  object
 9   winner_entry        152107 non-null  object
 10  winner_name         921321 non-null  object
 11  winner_hand         901856 non-null  object
 12  winner_ht           571805 non-null  float64
 13  winner_ioc          921248 non-null  object
 14  winner_age          908185 non-null  float64
 15  loser_id            921321 non-null  int64
 16  loser_seed          199975 non-null  object
 17  loser_entry         269749 non-null  object
 18  loser_name          921321 non-null  object
 19  loser_hand          900260 non-null  object
 20  loser_ht            459832 non-null  float64
 21  loser_ioc           921187 non-null  object
 22  loser_age           892809 non-null  float64
 23  score               921167 non-null  object
 24  best_of             921321 non-null  int64
 25  round               921321 non-null  object
 26  minutes             199328 non-null  float64
 27  w_ace               205860 non-null  float64
 28  w_df                205859 non-null  float64
 29  w_svpt              205859 non-null  float64
 30  w_1stIn             205859 non-null  float64
 31  w_1stWon            205859 non-null  float64
 32  w_2ndWon            205859 non-null  float64
 33  w_SvGms             205858 non-null  float64
 34  w_bpSaved           205859 non-null  float64
 35  w_bpFaced           205859 non-null  float64
 36  l_ace               205859 non-null  float64
 37  l_df                205860 non-null  float64
 38  l_svpt              205859 non-null  float64
 39  l_1stIn             205859 non-null  float64
 40  l_1stWon            205859 non-null  float64
 41  l_2ndWon            205859 non-null  float64
 42  l_SvGms             205858 non-null  float64
 43  l_bpSaved           205860 non-null  float64
 44  l_bpFaced           205860 non-null  float64
 45  winner_rank         813485 non-null  float64
 46  winner_rank_points  745187 non-null  float64
 47  loser_rank          746202 non-null  float64
 48  loser_rank_points   686508 non-null  float64
dtypes: float64(27), int64(5), object(17)
memory usage: 344.4+ MB

In [5]:
# Create a new DataFrame containing only rows where the "surface" column has NaN values
df_used[df_used["surface"].isna()]

,tourney_id,tourney_name,surface,draw_size,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
939,1968-D001,Davis Cup SAM QF: VEN vs ARG,NaN,4.0,D,19680427,1,100136,NaN,NaN,Humphrey Hose,R,NaN,VEN,20.900000,100172,NaN,NaN,Tito Vazquez,R,173.0,ARG,19.300000,4-6 6-3 8-6 6-1,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
940,1968-D001,Davis Cup SAM QF: VEN vs ARG,NaN,4.0,D,19680427,2,100258,NaN,NaN,Jorge Andrew,R,NaN,VEN,16.400000,110413,NaN,NaN,Norberto Herrero,U,NaN,UNK,21.400000,13-15 6-4 7-5 6-4,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
941,1968-D001,Davis Cup SAM QF: VEN vs ARG,NaN,4.0,D,19680427,4,100172,NaN,NaN,Tito Vazquez,R,173.0,ARG,19.300000,100258,NaN,NaN,Jorge Andrew,R,NaN,VEN,16.400000,6-1 6-4 6-1,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
942,1968-D001,Davis Cup SAM QF: VEN vs ARG,NaN,4.0,D,19680427,5,100136,NaN,NaN,Humphrey Hose,R,NaN,VEN,20.900000,110413,NaN,NaN,Norberto Herrero,U,NaN,UNK,21.400000,6-2 6-2 6-2,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
947,1968-D003,Davis Cup EUR R1: AUT vs RSA,NaN,4.0,D,19680503,1,100121,NaN,NaN,Raymond Moore,R,183.0,RSA,21.600000,109757,NaN,NaN,Detler Herdy,R,NaN,AUT,26.500000,6-1 6-2 6-4,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218329,1967-D046,Davis Cup EUR R1: MON vs TUR,NaN,4,D,19670428,5,111082,NaN,NaN,Adrien Viviani,U,NaN,MON,NaN,111106,NaN,NaN,Tahsin Gursoy,U,NaN,TUR,22.661191,6-4 1-6 3-6 6-4 6-4,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218334,1967-D048,Davis Cup AME SF: PHI vs VIE,NaN,4,D,19670414,1,106910,NaN,NaN,Eddie Cruz,R,NaN,PHI,NaN,111097,NaN,NaN,Van Bay Vo,U,NaN,VIE,NaN,6-2 6-3 6-2,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218335,1967-D048,Davis Cup AME SF: PHI vs VIE,NaN,4,D,19670414,2,112556,NaN,NaN,Felicisimo Ampon,NaN,NaN,PHI,46.461328,111091,NaN,NaN,Van Thanh Vo,U,NaN,VIE,NaN,6-4 6-1 6-1,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218336,1967-D048,Davis Cup AME SF: PHI vs VIE,NaN,4,D,19670414,4,125731,NaN,NaN,Samuel Ang,U,NaN,PHI,NaN,117339,NaN,NaN,Hoang Duc Luu,NaN,NaN,VIE,NaN,6-3 6-4 6-1,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
218337,1967-D048,Davis Cup AME SF: PHI vs VIE,NaN,4,D,19670414,5,106910,NaN,NaN,Eddie Cruz,R,NaN,PHI,NaN,111091,NaN,NaN,Van Thanh Vo,U,NaN,VIE,NaN,12-10 9-7 6-1,5,RR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df_used.dropna(subset=["surface"], inplace=True) #Drop the surface columns that contain "NaN" value
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 916692 entries, 0 to 921320
Data columns (total 49 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          916692 non-null  object
 1   tourney_name        916692 non-null  object
 2   surface             916692 non-null  object
 3   draw_size           916478 non-null  object
 4   tourney_level       916692 non-null  object
 5   tourney_date        916692 non-null  int64
 6   match_num           916692 non-null  int64
 7   winner_id           916692 non-null  int64
 8   winner_seed         389900 non-null  object
 9   winner_entry        152107 non-null  object
 10  winner_name         916692 non-null  object
 11  winner_hand         898357 non-null  object
 12  winner_ht           570176 non-null  float64
 13  winner_ioc          916619 non-null  object
 14  winner_age          904141 non-null  float64
 15  loser_id            916692 non-null  int64
 16  loser_seed          199933 non-null  object
 17  loser_entry         269749 non-null  object
 18  loser_name          916692 non-null  object
 19  loser_hand          896669 non-null  object
 20  loser_ht            458782 non-null  float64
 21  loser_ioc           916566 non-null  object
 22  loser_age           889420 non-null  float64
 23  score               916538 non-null  object
 24  best_of             916692 non-null  int64
 25  round               916692 non-null  object
 26  minutes             199328 non-null  float64
 27  w_ace               205860 non-null  float64
 28  w_df                205859 non-null  float64
 29  w_svpt              205859 non-null  float64
 30  w_1stIn             205859 non-null  float64
 31  w_1stWon            205859 non-null  float64
 32  w_2ndWon            205859 non-null  float64
 33  w_SvGms             205858 non-null  float64
 34  w_bpSaved           205859 non-null  float64
 35  w_bpFaced           205859 non-null  float64
 36  l_ace               205859 non-null  float64
 37  l_df                205860 non-null  float64
 38  l_svpt              205859 non-null  float64
 39  l_1stIn             205859 non-null  float64
 40  l_1stWon            205859 non-null  float64
 41  l_2ndWon            205859 non-null  float64
 42  l_SvGms             205858 non-null  float64
 43  l_bpSaved           205860 non-null  float64
 44  l_bpFaced           205860 non-null  float64
 45  winner_rank         812596 non-null  float64
 46  winner_rank_points  745074 non-null  float64
 47  loser_rank          745532 non-null  float64
 48  loser_rank_points   686415 non-null  float64
dtypes: float64(27), int64(5), object(17)
memory usage: 349.7+ MB

In [7]:
# Remove the draw_size columns since it is not effect the match outcome. 
df_used.drop(columns=["draw_size"], inplace= True)
df_used

,tourney_id,tourney_name,surface,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,1968-2029,Dublin,Grass,A,19680708,270,112411,NaN,NaN,Doug Smith,U,NaN,AUS,NaN,110196,NaN,NaN,Peter Ledbetter,U,NaN,IRL,24.0,6-1 7-5,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1968-2029,Dublin,Grass,A,19680708,271,126914,NaN,NaN,Louis Pretorius,R,NaN,RSA,NaN,209536,NaN,NaN,Maurice Pollock,U,NaN,IRL,NaN,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1968-2029,Dublin,Grass,A,19680708,272,209523,NaN,NaN,Cecil Pedlow,U,NaN,IRL,NaN,209535,NaN,NaN,John Mulvey,U,NaN,IRL,NaN,6-2 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1968-2029,Dublin,Grass,A,19680708,273,100084,NaN,NaN,Tom Okker,R,178.0,NED,24.3,209534,NaN,NaN,Unknown Fearmon,U,NaN,NaN,NaN,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1968-2029,Dublin,Grass,A,19680708,274,100132,NaN,NaN,Armistead Neely,R,NaN,USA,21.3,209533,NaN,NaN,Harry Sheridan,U,NaN,IRL,NaN,6-2 6-4,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
921316,2024-2869,Skopje CH,Clay,C,20240520,241,210053,8.0,NaN,Luka Mikrut,U,NaN,CRO,20.0,103872,NaN,WC,Dimitar Grabuloski,U,NaN,MKD,42.5,6-3 6-4,3,Q1,87.0,4.0,6.0,64.0,31.0,24.0,18.0,10.0,2.0,3.0,2.0,5.0,78.0,43.0,30.0,13.0,9.0,6.0,9.0,511.0,76.0,NaN,NaN
921317,2024-2869,Skopje CH,Clay,C,20240520,240,208843,5.0,NaN,Jerome Kym,R,198.0,SUI,21.2,210078,NaN,WC,Berk Bugarikj,U,NaN,MKD,20.8,7-5 6-0,3,Q1,77.0,5.0,0.0,44.0,29.0,25.0,9.0,9.0,1.0,2.0,0.0,3.0,60.0,41.0,21.0,8.0,9.0,2.0,7.0,470.0,92.0,NaN,NaN
921318,2024-2869,Skopje CH,Clay,C,20240520,239,207484,12.0,NaN,Neil Oberleitner,R,NaN,AUT,24.7,200574,NaN,Alt,Alexander Donski,R,188.0,CAN,25.8,6-4 6-3,3,Q1,82.0,5.0,5.0,54.0,33.0,27.0,13.0,9.0,2.0,2.0,4.0,6.0,72.0,34.0,26.0,15.0,10.0,3.0,6.0,636.0,53.0,955.0,15.0
921319,2024-2869,Skopje CH,Clay,C,20240520,238,144970,6.0,NaN,Constantin Bittoun Kouzmine,L,NaN,FRA,25.3,212200,NaN,WC,Amar Huseinovic,U,NaN,MKD,NaN,6-0 6-1,3,Q1,59.0,0.0,1.0,43.0,32.0,26.0,5.0,7.0,4.0,4.0,2.0,0.0,36.0,22.0,9.0,4.0,6.0,0.0,5.0,487.0,87.0,NaN,NaN
921320,2024-2869,Skopje CH,Clay,C,20240520,237,202342,NaN,NaN,Ryan Seggerman,U,NaN,USA,24.7,106254,NaN,Alt,Calum Puttergill,U,NaN,AUS,30.5,7-5 6-0,3,Q1,56.0,10.0,1.0,44.0,28.0,22.0,12.0,9.0,0.0,1.0,0.0,9.0,52.0,28.0,19.0,7.0,9.0,3.0,8.0,555.0,67.0,880.0,20.0

In [8]:
# Convert the 'date' column to proper date format (YYYY-MM-DD)
df_used['tourney_date'] = pd.to_datetime(df_used['tourney_date'], format='%Y%m%d')
df_used.head(10)

,tourney_id,tourney_name,surface,tourney_level,tourney_date,match_num,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,1968-2029,Dublin,Grass,A,1968-07-08,270,112411,NaN,NaN,Doug Smith,U,NaN,AUS,NaN,110196,NaN,NaN,Peter Ledbetter,U,NaN,IRL,24.0,6-1 7-5,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1968-2029,Dublin,Grass,A,1968-07-08,271,126914,NaN,NaN,Louis Pretorius,R,NaN,RSA,NaN,209536,NaN,NaN,Maurice Pollock,U,NaN,IRL,NaN,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1968-2029,Dublin,Grass,A,1968-07-08,272,209523,NaN,NaN,Cecil Pedlow,U,NaN,IRL,NaN,209535,NaN,NaN,John Mulvey,U,NaN,IRL,NaN,6-2 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1968-2029,Dublin,Grass,A,1968-07-08,273,100084,NaN,NaN,Tom Okker,R,178.0,NED,24.3,209534,NaN,NaN,Unknown Fearmon,U,NaN,NaN,NaN,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1968-2029,Dublin,Grass,A,1968-07-08,274,100132,NaN,NaN,Armistead Neely,R,NaN,USA,21.3,209533,NaN,NaN,Harry Sheridan,U,NaN,IRL,NaN,6-2 6-4,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1968-2029,Dublin,Grass,A,1968-07-08,275,207073,NaN,NaN,John Mcgrath,U,NaN,IRL,NaN,209532,NaN,NaN,Brendan Kelly,U,NaN,IRL,NaN,4-6 8-6 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1968-2029,Dublin,Grass,A,1968-07-08,276,109783,NaN,NaN,Bob Howe,R,183.0,AUS,42.9,125672,NaN,NaN,Kenneth Reid,U,NaN,IRL,NaN,6-0 9-7,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1968-2029,Dublin,Grass,A,1968-07-08,277,109745,NaN,NaN,Lew Hoad,R,179.0,AUS,33.6,125716,NaN,NaN,Jim Buckley,U,NaN,IRL,31.2,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1968-2029,Dublin,Grass,A,1968-07-08,278,201749,NaN,NaN,Graydon Garner,R,NaN,RSA,23.0,113401,NaN,NaN,Vivian Gotto,U,NaN,IRL,46.8,6-1 6-0,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1968-2029,Dublin,Grass,A,1968-07-08,279,209525,NaN,NaN,Des Foley,U,NaN,IRL,NaN,110045,NaN,NaN,Peter Mockler,R,NaN,IRL,NaN,4-6 6-4 6-0,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
# Remove the match_num columns since it is not effect the match outcome. 
df_used.drop(columns=["match_num"], inplace= True)
df_used.head(10)

,tourney_id,tourney_name,surface,tourney_level,tourney_date,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,1968-2029,Dublin,Grass,A,1968-07-08,112411,NaN,NaN,Doug Smith,U,NaN,AUS,NaN,110196,NaN,NaN,Peter Ledbetter,U,NaN,IRL,24.0,6-1 7-5,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1968-2029,Dublin,Grass,A,1968-07-08,126914,NaN,NaN,Louis Pretorius,R,NaN,RSA,NaN,209536,NaN,NaN,Maurice Pollock,U,NaN,IRL,NaN,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1968-2029,Dublin,Grass,A,1968-07-08,209523,NaN,NaN,Cecil Pedlow,U,NaN,IRL,NaN,209535,NaN,NaN,John Mulvey,U,NaN,IRL,NaN,6-2 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1968-2029,Dublin,Grass,A,1968-07-08,100084,NaN,NaN,Tom Okker,R,178.0,NED,24.3,209534,NaN,NaN,Unknown Fearmon,U,NaN,NaN,NaN,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1968-2029,Dublin,Grass,A,1968-07-08,100132,NaN,NaN,Armistead Neely,R,NaN,USA,21.3,209533,NaN,NaN,Harry Sheridan,U,NaN,IRL,NaN,6-2 6-4,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1968-2029,Dublin,Grass,A,1968-07-08,207073,NaN,NaN,John Mcgrath,U,NaN,IRL,NaN,209532,NaN,NaN,Brendan Kelly,U,NaN,IRL,NaN,4-6 8-6 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1968-2029,Dublin,Grass,A,1968-07-08,109783,NaN,NaN,Bob Howe,R,183.0,AUS,42.9,125672,NaN,NaN,Kenneth Reid,U,NaN,IRL,NaN,6-0 9-7,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1968-2029,Dublin,Grass,A,1968-07-08,109745,NaN,NaN,Lew Hoad,R,179.0,AUS,33.6,125716,NaN,NaN,Jim Buckley,U,NaN,IRL,31.2,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1968-2029,Dublin,Grass,A,1968-07-08,201749,NaN,NaN,Graydon Garner,R,NaN,RSA,23.0,113401,NaN,NaN,Vivian Gotto,U,NaN,IRL,46.8,6-1 6-0,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1968-2029,Dublin,Grass,A,1968-07-08,209525,NaN,NaN,Des Foley,U,NaN,IRL,NaN,110045,NaN,NaN,Peter Mockler,R,NaN,IRL,NaN,4-6 6-4 6-0,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df_used["winner_seed"].fillna(0, inplace=True)
df_used.info()

<class 'pandas.core.frame.DataFrame'>
Index: 916692 entries, 0 to 921320
Data columns (total 47 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          916692 non-null  object
 1   tourney_name        916692 non-null  object
 2   surface             916692 non-null  object
 3   tourney_level       916692 non-null  object
 4   tourney_date        916692 non-null  datetime64[ns]
 5   winner_id           916692 non-null  int64
 6   winner_seed         916692 non-null  object
 7   winner_entry        152107 non-null  object
 8   winner_name         916692 non-null  object
 9   winner_hand         898357 non-null  object
 10  winner_ht           570176 non-null  float64
 11  winner_ioc          916619 non-null  object
 12  winner_age          904141 non-null  float64
 13  loser_id            916692 non-null  int64
 14  loser_seed          199933 non-null  object
 15  loser_entry         269749 non-null  object
 16  loser_name          916692 non-null  object
 17  loser_hand          896669 non-null  object
 18  loser_ht            458782 non-null  float64
 19  loser_ioc           916566 non-null  object
 20  loser_age           889420 non-null  float64
 21  score               916538 non-null  object
 22  best_of             916692 non-null  int64
 23  round               916692 non-null  object
 24  minutes             199328 non-null  float64
 25  w_ace               205860 non-null  float64
 26  w_df                205859 non-null  float64
 27  w_svpt              205859 non-null  float64
 28  w_1stIn             205859 non-null  float64
 29  w_1stWon            205859 non-null  float64
 30  w_2ndWon            205859 non-null  float64
 31  w_SvGms             205858 non-null  float64
 32  w_bpSaved           205859 non-null  float64
 33  w_bpFaced           205859 non-null  float64
 34  l_ace               205859 non-null  float64
 35  l_df                205860 non-null  float64
 36  l_svpt              205859 non-null  float64
 37  l_1stIn             205859 non-null  float64
 38  l_1stWon            205859 non-null  float64
 39  l_2ndWon            205859 non-null  float64
 40  l_SvGms             205858 non-null  float64
 41  l_bpSaved           205860 non-null  float64
 42  l_bpFaced           205860 non-null  float64
 43  winner_rank         812596 non-null  float64
 44  winner_rank_points  745074 non-null  float64
 45  loser_rank          745532 non-null  float64
 46  loser_rank_points   686415 non-null  float64
dtypes: datetime64[ns](1), float64(27), int64(3), object(16)
memory usage: 335.7+ MB

In [19]:
df_used.head(10)

,tourney_id,tourney_name,surface,tourney_level,tourney_date,winner_id,winner_seed,winner_entry,winner_name,winner_hand,winner_ht,winner_ioc,winner_age,loser_id,loser_seed,loser_entry,loser_name,loser_hand,loser_ht,loser_ioc,loser_age,score,best_of,round,minutes,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced,winner_rank,winner_rank_points,loser_rank,loser_rank_points
0,1968-2029,Dublin,Grass,A,1968-07-08,112411,0,NaN,Doug Smith,U,NaN,AUS,NaN,110196,NaN,NaN,Peter Ledbetter,U,NaN,IRL,24.0,6-1 7-5,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1968-2029,Dublin,Grass,A,1968-07-08,126914,0,NaN,Louis Pretorius,R,NaN,RSA,NaN,209536,NaN,NaN,Maurice Pollock,U,NaN,IRL,NaN,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1968-2029,Dublin,Grass,A,1968-07-08,209523,0,NaN,Cecil Pedlow,U,NaN,IRL,NaN,209535,NaN,NaN,John Mulvey,U,NaN,IRL,NaN,6-2 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1968-2029,Dublin,Grass,A,1968-07-08,100084,0,NaN,Tom Okker,R,178.0,NED,24.3,209534,NaN,NaN,Unknown Fearmon,U,NaN,NaN,NaN,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1968-2029,Dublin,Grass,A,1968-07-08,100132,0,NaN,Armistead Neely,R,NaN,USA,21.3,209533,NaN,NaN,Harry Sheridan,U,NaN,IRL,NaN,6-2 6-4,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1968-2029,Dublin,Grass,A,1968-07-08,207073,0,NaN,John Mcgrath,U,NaN,IRL,NaN,209532,NaN,NaN,Brendan Kelly,U,NaN,IRL,NaN,4-6 8-6 6-2,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1968-2029,Dublin,Grass,A,1968-07-08,109783,0,NaN,Bob Howe,R,183.0,AUS,42.9,125672,NaN,NaN,Kenneth Reid,U,NaN,IRL,NaN,6-0 9-7,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1968-2029,Dublin,Grass,A,1968-07-08,109745,0,NaN,Lew Hoad,R,179.0,AUS,33.6,125716,NaN,NaN,Jim Buckley,U,NaN,IRL,31.2,6-1 6-1,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1968-2029,Dublin,Grass,A,1968-07-08,201749,0,NaN,Graydon Garner,R,NaN,RSA,23.0,113401,NaN,NaN,Vivian Gotto,U,NaN,IRL,46.8,6-1 6-0,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1968-2029,Dublin,Grass,A,1968-07-08,209525,0,NaN,Des Foley,U,NaN,IRL,NaN,110045,NaN,NaN,Peter Mockler,R,NaN,IRL,NaN,4-6 6-4 6-0,3,R32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# Remove the winner_entry columns since it contains too much NaN value. 
df_used.drop(columns=["winner_entry"], inplace= True)

In [21]:
# Remove the winner_ht columns since it won't give any effect to the match outcome. 
df_used.drop(columns=["winner_ht"], inplace= True)

In [22]:
df_used.info()

<class 'pandas.core.frame.DataFrame'>
Index: 916692 entries, 0 to 921320
Data columns (total 45 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          916692 non-null  object
 1   tourney_name        916692 non-null  object
 2   surface             916692 non-null  object
 3   tourney_level       916692 non-null  object
 4   tourney_date        916692 non-null  datetime64[ns]
 5   winner_id           916692 non-null  int64
 6   winner_seed         916692 non-null  object
 7   winner_name         916692 non-null  object
 8   winner_hand         898357 non-null  object
 9   winner_ioc          916619 non-null  object
 10  winner_age          904141 non-null  float64
 11  loser_id            916692 non-null  int64
 12  loser_seed          199933 non-null  object
 13  loser_entry         269749 non-null  object
 14  loser_name          916692 non-null  object
 15  loser_hand          896669 non-null  object
 16  loser_ht            458782 non-null  float64
 17  loser_ioc           916566 non-null  object
 18  loser_age           889420 non-null  float64
 19  score               916538 non-null  object
 20  best_of             916692 non-null  int64
 21  round               916692 non-null  object
 22  minutes             199328 non-null  float64
 23  w_ace               205860 non-null  float64
 24  w_df                205859 non-null  float64
 25  w_svpt              205859 non-null  float64
 26  w_1stIn             205859 non-null  float64
 27  w_1stWon            205859 non-null  float64
 28  w_2ndWon            205859 non-null  float64
 29  w_SvGms             205858 non-null  float64
 30  w_bpSaved           205859 non-null  float64
 31  w_bpFaced           205859 non-null  float64
 32  l_ace               205859 non-null  float64
 33  l_df                205860 non-null  float64
 34  l_svpt              205859 non-null  float64
 35  l_1stIn             205859 non-null  float64
 36  l_1stWon            205859 non-null  float64
 37  l_2ndWon            205859 non-null  float64
 38  l_SvGms             205858 non-null  float64
 39  l_bpSaved           205860 non-null  float64
 40  l_bpFaced           205860 non-null  float64
 41  winner_rank         812596 non-null  float64
 42  winner_rank_points  745074 non-null  float64
 43  loser_rank          745532 non-null  float64
 44  loser_rank_points   686415 non-null  float64
dtypes: datetime64[ns](1), float64(26), int64(3), object(15)
memory usage: 321.7+ MB

In [23]:
df_used.dropna(subset=["winner_hand"], inplace=True) #Drop the surface columns that contain "NaN" value
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 898357 entries, 0 to 921320
Data columns (total 45 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          898357 non-null  object
 1   tourney_name        898357 non-null  object
 2   surface             898357 non-null  object
 3   tourney_level       898357 non-null  object
 4   tourney_date        898357 non-null  datetime64[ns]
 5   winner_id           898357 non-null  int64
 6   winner_seed         898357 non-null  object
 7   winner_name         898357 non-null  object
 8   winner_hand         898357 non-null  object
 9   winner_ioc          898284 non-null  object
 10  winner_age          891657 non-null  float64
 11  loser_id            898357 non-null  int64
 12  loser_seed          199917 non-null  object
 13  loser_entry         269722 non-null  object
 14  loser_name          898357 non-null  object
 15  loser_hand          895550 non-null  object
 16  loser_ht            458535 non-null  float64
 17  loser_ioc           898231 non-null  object
 18  loser_age           881378 non-null  float64
 19  score               898238 non-null  object
 20  best_of             898357 non-null  int64
 21  round               898357 non-null  object
 22  minutes             199319 non-null  float64
 23  w_ace               205850 non-null  float64
 24  w_df                205849 non-null  float64
 25  w_svpt              205849 non-null  float64
 26  w_1stIn             205849 non-null  float64
 27  w_1stWon            205849 non-null  float64
 28  w_2ndWon            205849 non-null  float64
 29  w_SvGms             205848 non-null  float64
 30  w_bpSaved           205849 non-null  float64
 31  w_bpFaced           205849 non-null  float64
 32  l_ace               205849 non-null  float64
 33  l_df                205850 non-null  float64
 34  l_svpt              205849 non-null  float64
 35  l_1stIn             205849 non-null  float64
 36  l_1stWon            205849 non-null  float64
 37  l_2ndWon            205849 non-null  float64
 38  l_SvGms             205848 non-null  float64
 39  l_bpSaved           205850 non-null  float64
 40  l_bpFaced           205850 non-null  float64
 41  winner_rank         812520 non-null  float64
 42  winner_rank_points  744998 non-null  float64
 43  loser_rank          745460 non-null  float64
 44  loser_rank_points   686343 non-null  float64
dtypes: datetime64[ns](1), float64(26), int64(3), object(15)
memory usage: 315.3+ MB

In [24]:
df_used.dropna(subset=["winner_ioc"], inplace=True) #Drop the surface columns that contain "NaN" value
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 898284 entries, 0 to 921320
Data columns (total 45 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          898284 non-null  object
 1   tourney_name        898284 non-null  object
 2   surface             898284 non-null  object
 3   tourney_level       898284 non-null  object
 4   tourney_date        898284 non-null  datetime64[ns]
 5   winner_id           898284 non-null  int64
 6   winner_seed         898284 non-null  object
 7   winner_name         898284 non-null  object
 8   winner_hand         898284 non-null  object
 9   winner_ioc          898284 non-null  object
 10  winner_age          891592 non-null  float64
 11  loser_id            898284 non-null  int64
 12  loser_seed          199899 non-null  object
 13  loser_entry         269703 non-null  object
 14  loser_name          898284 non-null  object
 15  loser_hand          895477 non-null  object
 16  loser_ht            458523 non-null  float64
 17  loser_ioc           898161 non-null  object
 18  loser_age           881315 non-null  float64
 19  score               898165 non-null  object
 20  best_of             898284 non-null  int64
 21  round               898284 non-null  object
 22  minutes             199303 non-null  float64
 23  w_ace               205834 non-null  float64
 24  w_df                205833 non-null  float64
 25  w_svpt              205833 non-null  float64
 26  w_1stIn             205833 non-null  float64
 27  w_1stWon            205833 non-null  float64
 28  w_2ndWon            205833 non-null  float64
 29  w_SvGms             205832 non-null  float64
 30  w_bpSaved           205833 non-null  float64
 31  w_bpFaced           205833 non-null  float64
 32  l_ace               205833 non-null  float64
 33  l_df                205834 non-null  float64
 34  l_svpt              205833 non-null  float64
 35  l_1stIn             205833 non-null  float64
 36  l_1stWon            205833 non-null  float64
 37  l_2ndWon            205833 non-null  float64
 38  l_SvGms             205832 non-null  float64
 39  l_bpSaved           205834 non-null  float64
 40  l_bpFaced           205834 non-null  float64
 41  winner_rank         812459 non-null  float64
 42  winner_rank_points  744937 non-null  float64
 43  loser_rank          745403 non-null  float64
 44  loser_rank_points   686286 non-null  float64
dtypes: datetime64[ns](1), float64(26), int64(3), object(15)
memory usage: 315.3+ MB

In [25]:
df_used.dropna(subset=["winner_age"], inplace=True) #Drop the surface columns that contain "NaN" value
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 891592 entries, 3 to 921320
Data columns (total 45 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          891592 non-null  object
 1   tourney_name        891592 non-null  object
 2   surface             891592 non-null  object
 3   tourney_level       891592 non-null  object
 4   tourney_date        891592 non-null  datetime64[ns]
 5   winner_id           891592 non-null  int64
 6   winner_seed         891592 non-null  object
 7   winner_name         891592 non-null  object
 8   winner_hand         891592 non-null  object
 9   winner_ioc          891592 non-null  object
 10  winner_age          891592 non-null  float64
 11  loser_id            891592 non-null  int64
 12  loser_seed          198711 non-null  object
 13  loser_entry         267677 non-null  object
 14  loser_name          891592 non-null  object
 15  loser_hand          888957 non-null  object
 16  loser_ht            456784 non-null  float64
 17  loser_ioc           891485 non-null  object
 18  loser_age           876015 non-null  float64
 19  score               891475 non-null  object
 20  best_of             891592 non-null  int64
 21  round               891592 non-null  object
 22  minutes             199278 non-null  float64
 23  w_ace               205809 non-null  float64
 24  w_df                205808 non-null  float64
 25  w_svpt              205808 non-null  float64
 26  w_1stIn             205808 non-null  float64
 27  w_1stWon            205808 non-null  float64
 28  w_2ndWon            205808 non-null  float64
 29  w_SvGms             205807 non-null  float64
 30  w_bpSaved           205808 non-null  float64
 31  w_bpFaced           205808 non-null  float64
 32  l_ace               205808 non-null  float64
 33  l_df                205809 non-null  float64
 34  l_svpt              205808 non-null  float64
 35  l_1stIn             205808 non-null  float64
 36  l_1stWon            205808 non-null  float64
 37  l_2ndWon            205808 non-null  float64
 38  l_SvGms             205807 non-null  float64
 39  l_bpSaved           205808 non-null  float64
 40  l_bpFaced           205808 non-null  float64
 41  winner_rank         808795 non-null  float64
 42  winner_rank_points  741929 non-null  float64
 43  loser_rank          741788 non-null  float64
 44  loser_rank_points   683313 non-null  float64
dtypes: datetime64[ns](1), float64(26), int64(3), object(15)
memory usage: 312.9+ MB

In [26]:
df_used["loser_seed"].fillna(0, inplace=True)
df_used.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891592 entries, 3 to 921320
Data columns (total 45 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          891592 non-null  object
 1   tourney_name        891592 non-null  object
 2   surface             891592 non-null  object
 3   tourney_level       891592 non-null  object
 4   tourney_date        891592 non-null  datetime64[ns]
 5   winner_id           891592 non-null  int64
 6   winner_seed         891592 non-null  object
 7   winner_name         891592 non-null  object
 8   winner_hand         891592 non-null  object
 9   winner_ioc          891592 non-null  object
 10  winner_age          891592 non-null  float64
 11  loser_id            891592 non-null  int64
 12  loser_seed          891592 non-null  object
 13  loser_entry         267677 non-null  object
 14  loser_name          891592 non-null  object
 15  loser_hand          888957 non-null  object
 16  loser_ht            456784 non-null  float64
 17  loser_ioc           891485 non-null  object
 18  loser_age           876015 non-null  float64
 19  score               891475 non-null  object
 20  best_of             891592 non-null  int64
 21  round               891592 non-null  object
 22  minutes             199278 non-null  float64
 23  w_ace               205809 non-null  float64
 24  w_df                205808 non-null  float64
 25  w_svpt              205808 non-null  float64
 26  w_1stIn             205808 non-null  float64
 27  w_1stWon            205808 non-null  float64
 28  w_2ndWon            205808 non-null  float64
 29  w_SvGms             205807 non-null  float64
 30  w_bpSaved           205808 non-null  float64
 31  w_bpFaced           205808 non-null  float64
 32  l_ace               205808 non-null  float64
 33  l_df                205809 non-null  float64
 34  l_svpt              205808 non-null  float64
 35  l_1stIn             205808 non-null  float64
 36  l_1stWon            205808 non-null  float64
 37  l_2ndWon            205808 non-null  float64
 38  l_SvGms             205807 non-null  float64
 39  l_bpSaved           205808 non-null  float64
 40  l_bpFaced           205808 non-null  float64
 41  winner_rank         808795 non-null  float64
 42  winner_rank_points  741929 non-null  float64
 43  loser_rank          741788 non-null  float64
 44  loser_rank_points   683313 non-null  float64
dtypes: datetime64[ns](1), float64(26), int64(3), object(15)
memory usage: 312.9+ MB

In [27]:
# Remove the winner_entry columns since it contains too much NaN value. 
df_used.drop(columns=["loser_entry"], inplace= True)

In [28]:
df_used.info()

<class 'pandas.core.frame.DataFrame'>
Index: 891592 entries, 3 to 921320
Data columns (total 44 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          891592 non-null  object
 1   tourney_name        891592 non-null  object
 2   surface             891592 non-null  object
 3   tourney_level       891592 non-null  object
 4   tourney_date        891592 non-null  datetime64[ns]
 5   winner_id           891592 non-null  int64
 6   winner_seed         891592 non-null  object
 7   winner_name         891592 non-null  object
 8   winner_hand         891592 non-null  object
 9   winner_ioc          891592 non-null  object
 10  winner_age          891592 non-null  float64
 11  loser_id            891592 non-null  int64
 12  loser_seed          891592 non-null  object
 13  loser_name          891592 non-null  object
 14  loser_hand          888957 non-null  object
 15  loser_ht            456784 non-null  float64
 16  loser_ioc           891485 non-null  object
 17  loser_age           876015 non-null  float64
 18  score               891475 non-null  object
 19  best_of             891592 non-null  int64
 20  round               891592 non-null  object
 21  minutes             199278 non-null  float64
 22  w_ace               205809 non-null  float64
 23  w_df                205808 non-null  float64
 24  w_svpt              205808 non-null  float64
 25  w_1stIn             205808 non-null  float64
 26  w_1stWon            205808 non-null  float64
 27  w_2ndWon            205808 non-null  float64
 28  w_SvGms             205807 non-null  float64
 29  w_bpSaved           205808 non-null  float64
 30  w_bpFaced           205808 non-null  float64
 31  l_ace               205808 non-null  float64
 32  l_df                205809 non-null  float64
 33  l_svpt              205808 non-null  float64
 34  l_1stIn             205808 non-null  float64
 35  l_1stWon            205808 non-null  float64
 36  l_2ndWon            205808 non-null  float64
 37  l_SvGms             205807 non-null  float64
 38  l_bpSaved           205808 non-null  float64
 39  l_bpFaced           205808 non-null  float64
 40  winner_rank         808795 non-null  float64
 41  winner_rank_points  741929 non-null  float64
 42  loser_rank          741788 non-null  float64
 43  loser_rank_points   683313 non-null  float64
dtypes: datetime64[ns](1), float64(26), int64(3), object(14)
memory usage: 306.1+ MB

In [29]:
df_used.dropna(subset=["loser_hand"], inplace=True) #Drop the surface columns that contain "NaN" value
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 888957 entries, 3 to 921320
Data columns (total 44 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          888957 non-null  object
 1   tourney_name        888957 non-null  object
 2   surface             888957 non-null  object
 3   tourney_level       888957 non-null  object
 4   tourney_date        888957 non-null  datetime64[ns]
 5   winner_id           888957 non-null  int64
 6   winner_seed         888957 non-null  object
 7   winner_name         888957 non-null  object
 8   winner_hand         888957 non-null  object
 9   winner_ioc          888957 non-null  object
 10  winner_age          888957 non-null  float64
 11  loser_id            888957 non-null  int64
 12  loser_seed          888957 non-null  object
 13  loser_name          888957 non-null  object
 14  loser_hand          888957 non-null  object
 15  loser_ht            456741 non-null  float64
 16  loser_ioc           888850 non-null  object
 17  loser_age           874439 non-null  float64
 18  score               888841 non-null  object
 19  best_of             888957 non-null  int64
 20  round               888957 non-null  object
 21  minutes             199230 non-null  float64
 22  w_ace               205759 non-null  float64
 23  w_df                205758 non-null  float64
 24  w_svpt              205758 non-null  float64
 25  w_1stIn             205758 non-null  float64
 26  w_1stWon            205758 non-null  float64
 27  w_2ndWon            205758 non-null  float64
 28  w_SvGms             205757 non-null  float64
 29  w_bpSaved           205758 non-null  float64
 30  w_bpFaced           205758 non-null  float64
 31  l_ace               205758 non-null  float64
 32  l_df                205759 non-null  float64
 33  l_svpt              205758 non-null  float64
 34  l_1stIn             205758 non-null  float64
 35  l_1stWon            205758 non-null  float64
 36  l_2ndWon            205758 non-null  float64
 37  l_SvGms             205757 non-null  float64
 38  l_bpSaved           205758 non-null  float64
 39  l_bpFaced           205758 non-null  float64
 40  winner_rank         808565 non-null  float64
 41  winner_rank_points  741699 non-null  float64
 42  loser_rank          741654 non-null  float64
 43  loser_rank_points   683179 non-null  float64
dtypes: datetime64[ns](1), float64(26), int64(3), object(14)
memory usage: 305.2+ MB

In [30]:
# Remove the winner_entry columns since it contains too much NaN value. 
df_used.drop(columns=["loser_ht"], inplace= True)

In [31]:
df_used.info()

<class 'pandas.core.frame.DataFrame'>
Index: 888957 entries, 3 to 921320
Data columns (total 43 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          888957 non-null  object
 1   tourney_name        888957 non-null  object
 2   surface             888957 non-null  object
 3   tourney_level       888957 non-null  object
 4   tourney_date        888957 non-null  datetime64[ns]
 5   winner_id           888957 non-null  int64
 6   winner_seed         888957 non-null  object
 7   winner_name         888957 non-null  object
 8   winner_hand         888957 non-null  object
 9   winner_ioc          888957 non-null  object
 10  winner_age          888957 non-null  float64
 11  loser_id            888957 non-null  int64
 12  loser_seed          888957 non-null  object
 13  loser_name          888957 non-null  object
 14  loser_hand          888957 non-null  object
 15  loser_ioc           888850 non-null  object
 16  loser_age           874439 non-null  float64
 17  score               888841 non-null  object
 18  best_of             888957 non-null  int64
 19  round               888957 non-null  object
 20  minutes             199230 non-null  float64
 21  w_ace               205759 non-null  float64
 22  w_df                205758 non-null  float64
 23  w_svpt              205758 non-null  float64
 24  w_1stIn             205758 non-null  float64
 25  w_1stWon            205758 non-null  float64
 26  w_2ndWon            205758 non-null  float64
 27  w_SvGms             205757 non-null  float64
 28  w_bpSaved           205758 non-null  float64
 29  w_bpFaced           205758 non-null  float64
 30  l_ace               205758 non-null  float64
 31  l_df                205759 non-null  float64
 32  l_svpt              205758 non-null  float64
 33  l_1stIn             205758 non-null  float64
 34  l_1stWon            205758 non-null  float64
 35  l_2ndWon            205758 non-null  float64
 36  l_SvGms             205757 non-null  float64
 37  l_bpSaved           205758 non-null  float64
 38  l_bpFaced           205758 non-null  float64
 39  winner_rank         808565 non-null  float64
 40  winner_rank_points  741699 non-null  float64
 41  loser_rank          741654 non-null  float64
 42  loser_rank_points   683179 non-null  float64
dtypes: datetime64[ns](1), float64(25), int64(3), object(14)
memory usage: 298.4+ MB

In [32]:
df_used.dropna(subset=["loser_ioc"], inplace=True) #Drop the surface columns that contain "NaN" value
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 888850 entries, 4 to 921320
Data columns (total 43 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          888850 non-null  object
 1   tourney_name        888850 non-null  object
 2   surface             888850 non-null  object
 3   tourney_level       888850 non-null  object
 4   tourney_date        888850 non-null  datetime64[ns]
 5   winner_id           888850 non-null  int64
 6   winner_seed         888850 non-null  object
 7   winner_name         888850 non-null  object
 8   winner_hand         888850 non-null  object
 9   winner_ioc          888850 non-null  object
 10  winner_age          888850 non-null  float64
 11  loser_id            888850 non-null  int64
 12  loser_seed          888850 non-null  object
 13  loser_name          888850 non-null  object
 14  loser_hand          888850 non-null  object
 15  loser_ioc           888850 non-null  object
 16  loser_age           874378 non-null  float64
 17  score               888734 non-null  object
 18  best_of             888850 non-null  int64
 19  round               888850 non-null  object
 20  minutes             199219 non-null  float64
 21  w_ace               205746 non-null  float64
 22  w_df                205745 non-null  float64
 23  w_svpt              205745 non-null  float64
 24  w_1stIn             205745 non-null  float64
 25  w_1stWon            205745 non-null  float64
 26  w_2ndWon            205745 non-null  float64
 27  w_SvGms             205744 non-null  float64
 28  w_bpSaved           205745 non-null  float64
 29  w_bpFaced           205745 non-null  float64
 30  l_ace               205745 non-null  float64
 31  l_df                205746 non-null  float64
 32  l_svpt              205745 non-null  float64
 33  l_1stIn             205745 non-null  float64
 34  l_1stWon            205745 non-null  float64
 35  l_2ndWon            205745 non-null  float64
 36  l_SvGms             205744 non-null  float64
 37  l_bpSaved           205745 non-null  float64
 38  l_bpFaced           205745 non-null  float64
 39  winner_rank         808506 non-null  float64
 40  winner_rank_points  741641 non-null  float64
 41  loser_rank          741610 non-null  float64
 42  loser_rank_points   683135 non-null  float64
dtypes: datetime64[ns](1), float64(25), int64(3), object(14)
memory usage: 298.4+ MB

In [33]:
df_used.dropna(subset=["loser_age"], inplace=True) #Drop the surface columns that contain "NaN" value
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 874378 entries, 7 to 921320
Data columns (total 43 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          874378 non-null  object
 1   tourney_name        874378 non-null  object
 2   surface             874378 non-null  object
 3   tourney_level       874378 non-null  object
 4   tourney_date        874378 non-null  datetime64[ns]
 5   winner_id           874378 non-null  int64
 6   winner_seed         874378 non-null  object
 7   winner_name         874378 non-null  object
 8   winner_hand         874378 non-null  object
 9   winner_ioc          874378 non-null  object
 10  winner_age          874378 non-null  float64
 11  loser_id            874378 non-null  int64
 12  loser_seed          874378 non-null  object
 13  loser_name          874378 non-null  object
 14  loser_hand          874378 non-null  object
 15  loser_ioc           874378 non-null  object
 16  loser_age           874378 non-null  float64
 17  score               874284 non-null  object
 18  best_of             874378 non-null  int64
 19  round               874378 non-null  object
 20  minutes             198971 non-null  float64
 21  w_ace               205497 non-null  float64
 22  w_df                205497 non-null  float64
 23  w_svpt              205497 non-null  float64
 24  w_1stIn             205497 non-null  float64
 25  w_1stWon            205497 non-null  float64
 26  w_2ndWon            205497 non-null  float64
 27  w_SvGms             205496 non-null  float64
 28  w_bpSaved           205497 non-null  float64
 29  w_bpFaced           205497 non-null  float64
 30  l_ace               205497 non-null  float64
 31  l_df                205497 non-null  float64
 32  l_svpt              205497 non-null  float64
 33  l_1stIn             205497 non-null  float64
 34  l_1stWon            205497 non-null  float64
 35  l_2ndWon            205497 non-null  float64
 36  l_SvGms             205496 non-null  float64
 37  l_bpSaved           205497 non-null  float64
 38  l_bpFaced           205497 non-null  float64
 39  winner_rank         799179 non-null  float64
 40  winner_rank_points  734109 non-null  float64
 41  loser_rank          735851 non-null  float64
 42  loser_rank_points   678437 non-null  float64
dtypes: datetime64[ns](1), float64(25), int64(3), object(14)
memory usage: 293.5+ MB

In [38]:
# Remove the winner_entry columns since it contains too much NaN value. 
df_used.drop(columns=["minutes"], inplace= True)

In [39]:
df_used.info()

<class 'pandas.core.frame.DataFrame'>
Index: 874378 entries, 7 to 921320
Data columns (total 42 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          874378 non-null  object
 1   tourney_name        874378 non-null  object
 2   surface             874378 non-null  object
 3   tourney_level       874378 non-null  object
 4   tourney_date        874378 non-null  datetime64[ns]
 5   winner_id           874378 non-null  int64
 6   winner_seed         874378 non-null  object
 7   winner_name         874378 non-null  object
 8   winner_hand         874378 non-null  object
 9   winner_ioc          874378 non-null  object
 10  winner_age          874378 non-null  float64
 11  loser_id            874378 non-null  int64
 12  loser_seed          874378 non-null  object
 13  loser_name          874378 non-null  object
 14  loser_hand          874378 non-null  object
 15  loser_ioc           874378 non-null  object
 16  loser_age           874378 non-null  float64
 17  score               874284 non-null  object
 18  best_of             874378 non-null  int64
 19  round               874378 non-null  object
 20  w_ace               205497 non-null  float64
 21  w_df                205497 non-null  float64
 22  w_svpt              205497 non-null  float64
 23  w_1stIn             205497 non-null  float64
 24  w_1stWon            205497 non-null  float64
 25  w_2ndWon            205497 non-null  float64
 26  w_SvGms             205496 non-null  float64
 27  w_bpSaved           205497 non-null  float64
 28  w_bpFaced           205497 non-null  float64
 29  l_ace               205497 non-null  float64
 30  l_df                205497 non-null  float64
 31  l_svpt              205497 non-null  float64
 32  l_1stIn             205497 non-null  float64
 33  l_1stWon            205497 non-null  float64
 34  l_2ndWon            205497 non-null  float64
 35  l_SvGms             205496 non-null  float64
 36  l_bpSaved           205497 non-null  float64
 37  l_bpFaced           205497 non-null  float64
 38  winner_rank         799179 non-null  float64
 39  winner_rank_points  734109 non-null  float64
 40  loser_rank          735851 non-null  float64
 41  loser_rank_points   678437 non-null  float64
dtypes: datetime64[ns](1), float64(24), int64(3), object(14)
memory usage: 286.9+ MB

In [40]:
df_used.dropna(subset=["w_SvGms"], inplace=True) #Drop the surface columns that contain "NaN" value
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 205496 entries, 86621 to 921320
Data columns (total 42 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          205496 non-null  object
 1   tourney_name        205496 non-null  object
 2   surface             205496 non-null  object
 3   tourney_level       205496 non-null  object
 4   tourney_date        205496 non-null  datetime64[ns]
 5   winner_id           205496 non-null  int64
 6   winner_seed         205496 non-null  object
 7   winner_name         205496 non-null  object
 8   winner_hand         205496 non-null  object
 9   winner_ioc          205496 non-null  object
 10  winner_age          205496 non-null  float64
 11  loser_id            205496 non-null  int64
 12  loser_seed          205496 non-null  object
 13  loser_name          205496 non-null  object
 14  loser_hand          205496 non-null  object
 15  loser_ioc           205496 non-null  object
 16  loser_age           205496 non-null  float64
 17  score               205495 non-null  object
 18  best_of             205496 non-null  int64
 19  round               205496 non-null  object
 20  w_ace               205494 non-null  float64
 21  w_df                205494 non-null  float64
 22  w_svpt              205494 non-null  float64
 23  w_1stIn             205494 non-null  float64
 24  w_1stWon            205494 non-null  float64
 25  w_2ndWon            205494 non-null  float64
 26  w_SvGms             205496 non-null  float64
 27  w_bpSaved           205494 non-null  float64
 28  w_bpFaced           205494 non-null  float64
 29  l_ace               205494 non-null  float64
 30  l_df                205494 non-null  float64
 31  l_svpt              205494 non-null  float64
 32  l_1stIn             205494 non-null  float64
 33  l_1stWon            205494 non-null  float64
 34  l_2ndWon            205494 non-null  float64
 35  l_SvGms             205496 non-null  float64
 36  l_bpSaved           205494 non-null  float64
 37  l_bpFaced           205494 non-null  float64
 38  winner_rank         204296 non-null  float64
 39  winner_rank_points  203338 non-null  float64
 40  loser_rank          200872 non-null  float64
 41  loser_rank_points   199918 non-null  float64
dtypes: datetime64[ns](1), float64(24), int64(3), object(14)
memory usage: 67.4+ MB

In [41]:
df_used.dropna(subset=["w_ace"], inplace=True) #Drop the surface columns that contain "NaN" value
df_used.info ()

<class 'pandas.core.frame.DataFrame'>
Index: 205494 entries, 86621 to 921320
Data columns (total 42 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   tourney_id          205494 non-null  object
 1   tourney_name        205494 non-null  object
 2   surface             205494 non-null  object
 3   tourney_level       205494 non-null  object
 4   tourney_date        205494 non-null  datetime64[ns]
 5   winner_id           205494 non-null  int64
 6   winner_seed         205494 non-null  object
 7   winner_name         205494 non-null  object
 8   winner_hand         205494 non-null  object
 9   winner_ioc          205494 non-null  object
 10  winner_age          205494 non-null  float64
 11  loser_id            205494 non-null  int64
 12  loser_seed          205494 non-null  object
 13  loser_name          205494 non-null  object
 14  loser_hand          205494 non-null  object
 15  loser_ioc           205494 non-null  object
 16  loser_age           205494 non-null  float64
 17  score               205494 non-null  object
 18  best_of             205494 non-null  int64
 19  round               205494 non-null  object
 20  w_ace               205494 non-null  float64
 21  w_df                205494 non-null  float64
 22  w_svpt              205494 non-null  float64
 23  w_1stIn             205494 non-null  float64
 24  w_1stWon            205494 non-null  float64
 25  w_2ndWon            205494 non-null  float64
 26  w_SvGms             205494 non-null  float64
 27  w_bpSaved           205494 non-null  float64
 28  w_bpFaced           205494 non-null  float64
 29  l_ace               205494 non-null  float64
 30  l_df                205494 non-null  float64
 31  l_svpt              205494 non-null  float64
 32  l_1stIn             205494 non-null  float64
 33  l_1stWon            205494 non-null  float64
 34  l_2ndWon            205494 non-null  float64
 35  l_SvGms             205494 non-null  float64
 36  l_bpSaved           205494 non-null  float64
 37  l_bpFaced           205494 non-null  float64
 38  winner_rank         204294 non-null  float64
 39  winner_rank_points  203336 non-null  float64
 40  loser_rank          200870 non-null  float64
 41  loser_rank_points   199916 non-null  float64
dtypes: datetime64[ns](1), float64(24), int64(3), object(14)
memory usage: 67.4+ MB

In [42]:
# Remove the winner_entry columns since it contains too much NaN value. 
df_used.drop(columns=["winner_rank","winner_rank_points","loser_rank","loser_rank_points"], inplace= True)

### Cleaned Data Frame

In [46]:
df_used.sample (25)

,tourney_id,tourney_name,surface,tourney_level,tourney_date,winner_id,winner_seed,winner_name,winner_hand,winner_ioc,winner_age,loser_id,loser_seed,loser_name,loser_hand,loser_ioc,loser_age,score,best_of,round,w_ace,w_df,w_svpt,w_1stIn,w_1stWon,w_2ndWon,w_SvGms,w_bpSaved,w_bpFaced,l_ace,l_df,l_svpt,l_1stIn,l_1stWon,l_2ndWon,l_SvGms,l_bpSaved,l_bpFaced
133489,2004-315,Newport,Grass,A,2004-07-05,102257,0,Greg Rusedski,L,GBR,30.8,103319,0,Jeff Morrison,R,USA,25.4,7-6(5) 7-5,3,QF,9.0,2.0,69.0,45.0,35.0,14.0,12.0,0.0,1.0,8.0,4.0,78.0,53.0,39.0,11.0,12.0,1.0,3.0
869872,2018-5018,Burnie CH,Hard,C,2018-01-29,127157,0,Daniel Altmaier,R,GER,19.3,106186,7.0,Jason Kubler,R,AUS,24.6,6-3 2-6 6-2,3,SF,8.0,3.0,73.0,43.0,27.0,16.0,12.0,5.0,9.0,4.0,6.0,98.0,47.0,29.0,21.0,13.0,7.0,13.0
878434,2019-1796,St. Brieuc CH,Hard,C,2019-03-25,105575,1.0,Ricardas Berankis,R,LTU,28.7,123920,0,Gregoire Jacq,U,FRA,26.3,6-1 6-3,3,R32,0.0,2.0,43.0,22.0,18.0,11.0,8.0,0.0,1.0,1.0,0.0,55.0,39.0,22.0,4.0,8.0,5.0,10.0
919061,2024-9479,Santa Cruz De La Sierra CH,Clay,C,2024-03-04,207815,10.0,Guido Ivan Justo,U,ARG,26.2,210181,0,Tobias Franco,U,ARG,22.1,6-1 6-1,3,Q1,0.0,2.0,40.0,25.0,18.0,10.0,7.0,3.0,4.0,0.0,1.0,43.0,35.0,12.0,2.0,7.0,2.0,8.0
858629,2017-0603,Fergana CH,Hard,C,2017-06-19,200672,0,Sergey Fomin,R,UZB,16.3,110530,0,Andrey Yakovlev,R,RUS,24.8,6-3 6-1,3,R32,11.0,2.0,49.0,28.0,24.0,11.0,8.0,3.0,3.0,0.0,4.0,46.0,27.0,17.0,7.0,8.0,2.0,6.0
840507,2014-891,Chennai,Hard,A,2013-12-30,106368,0,Ramkumar Ramanathan,R,IND,19.1,111576,0,Sumit Nagal,R,IND,16.3,6-2 6-0,3,Q1,2.0,2.0,38.0,19.0,15.0,14.0,7.0,1.0,1.0,0.0,3.0,51.0,30.0,17.0,6.0,7.0,4.0,9.0
822533,2012-341,Metz,Hard,A,2012-09-17,104672,0,Vincent Millot,L,FRA,26.6,104023,0,Nicolas Renavand,R,FRA,30.2,7-6(8) 6-1,3,Q1,3.0,3.0,70.0,34.0,25.0,20.0,10.0,3.0,5.0,2.0,4.0,61.0,37.0,24.0,9.0,9.0,1.0,5.0
98227,1994-580,Australian Open,Hard,G,1994-01-17,102088,0,Joern Renzenbrink,R,GER,21.5,101750,0,Cristiano Caratti,R,ITA,23.6,6-1 6-4 6-4,5,R128,12.0,9.0,117.0,71.0,57.0,20.0,14.0,10.0,11.0,1.0,3.0,87.0,49.0,33.0,14.0,13.0,5.0,10.0
128323,2002-429,Stockholm,Hard,A,2002-10-21,102701,6.0,Marcelo Rios,L,CHI,26.8,101885,0,Wayne Arthurs,L,AUS,31.5,6-4 6-7(5) 6-1,3,R32,4.0,4.0,94.0,57.0,44.0,23.0,15.0,2.0,2.0,21.0,9.0,102.0,54.0,40.0,23.0,14.0,7.0,10.0
835479,2014-360,Casablanca,Clay,A,2014-04-07,106065,0,Marco Cecchinato,R,ITA,21.5,104803,0,Younes Rachidi,R,MAR,27.5,6-2 6-0,3,Q1,3.0,3.0,36.0,25.0,22.0,6.0,7.0,0.0,0.0,0.0,6.0,48.0,28.0,14.0,7.0,7.0,3.0,8.0
154478,2010-314,Gstaad,Clay,A,2010-07-25,104890,0,Andreas Haider Maurer,R,AUT,23.3,104797,0,Denis Istomin,R,UZB,23.8,6-3 6-7(5) 6-4,3,R32,8.0,1.0,110.0,63.0,47.0,23.0,16.0,6.0,8.0,11.0,6.0,109.0,73.0,48.0,17.0,15.0,7.0,11.0
919712,2024-7494,Barletta CH,Clay,C,2024-04-01,202354,2.0,Matthew Dellavedova,U,AUS,23.8,126627,0,Johan Nikles,R,SUI,27.0,6-1 7-5,3,Q1,0.0,4.0,75.0,55.0,35.0,12.0,10.0,9.0,10.0,0.0,1.0,51.0,37.0,16.0,9.0,9.0,5.0,9.0
87429,1991-403,Miami Masters,Hard,M,1991-03-15,101191,24.0,Richey Reneberg,R,USA,25.4,101733,0,Jan Siemerink,L,NED,20.9,7-6(5) 6-4,3,R32,1.0,0.0,63.0,43.0,34.0,12.0,11.0,1.0,2.0,9.0,4.0,81.0,37.0,31.0,19.0,11.0,3.0,5.0
181235,2019-0568,St. Petersburg,Hard,A,2019-09-16,106432,4.0,Borna Coric,R,CRO,22.8,105916,0,Marton Fucsovics,R,HUN,27.6,6-7(5) 7-5 3-0 RET,3,R16,1.0,4.0,94.0,52.0,38.0,25.0,14.0,3.0,4.0,5.0,5.0,94.0,53.0,40.0,19.0,13.0,2.0,5.0
822388,2012-337,Vienna,Hard,A,2012-10-15,104516,0,Arnau Brugues Davi,L,ESP,27.6,105821,0,Riccardo Bellotti,R,ITA,21.1,7-5 6-4,3,Q1,0.0,3.0,70.0,40.0,29.0,20.0,11.0,2.0,2.0,5.0,0.0,59.0,34.0,25.0,16.0,11.0,1.0,3.0
827292,2012-773,Bucharest,Clay,A,2012-04-23,105865,0,Andrei Savulescu,U,ROU,20.4,106389,0,Andrei Stefan Apostol,R,ROU,17.1,6-4 6-3,3,Q1,3.0,5.0,51.0,34.0,24.0,8.0,9.0,4.0,7.0,1.0,4.0,63.0,42.0,21.0,9.0,10.0,1.0,7.0
890310,2021-9452,Concepcion CH,Clay,C,2021-02-14,106249,0,Joao Domingues,R,POR,27.3,105529,0,Carlos Gomez Herrera,R,ESP,30.7,4-6 6-4 7-5,3,R32,1.0,1.0,102.0,68.0,43.0,18.0,16.0,2.0,5.0,0.0,3.0,100.0,78.0,51.0,11.0,16.0,2.0,6.0
920688,2024-2861,Cagliari CH,Clay,C,2024-04-29,207182,0,Emilio Nava,R,USA,22.3,132283,5.0,Lorenzo Sonego,R,ITA,28.9,7-6(4) 6-4,3,R16,5.0,4.0,84.0,40.0,28.0,25.0,11.0,9.0,11.0,1.0,4.0,68.0,44.0,31.0,9.0,11.0,2.0,5.0
184921,2021-540,Wimbledon,Grass,G,2021-06-28,106401,0,Nick Kyrgios,R,AUS,26.1,126149,0,Gianluca Mager,R,ITA,26.5,7-6(7) 6-4 6-4,5,R64,29.0,1.0,95.0,62.0,50.0,23.0,17.0,0.0,0.0,17.0,3.0,107.0,64.0,46.0,27.0,16.0,5.0,7.0
832797,2013-6714,West Lakes CH,Hard,C,2013-02-04,103565,0,Stephane Robert,R,FRA,32.7,105441,0,John Patrick Smith,L,AUS,24.0,7-6(4) 6-3,3,R16,1.0,0.0,63.0,35.0,25.0,21.0,11.0,2.0,4.0,3.0,0.0,69.0,46.0,31.0,10.0,10.0,5.0,8.0
879359,2019-520,Roland Garros,Clay,G,2019-05-27,111505,0,Enzo Couacaud,R,FRA,24.2,103893,3.0,Paolo Lorenzi,R,ITA,37.4,4-6 6-4 6-0,3,Q1,6.0,1.0,84.0,50.0,35.0,19.0,13.0,6.0,8.0,0.0,2.0,86.0,61.0,33.0,14.0,13.0,8.0,13.0
898236,2022-9693,Aguascalientes CH,Clay,C,2022-04-18,104905,7.0,Nicolas Barrientos,R,COL,34.9,207834,0,Juan Alejandro Hernandez Serrano,R,MEX,22.8,6-3 6-4,3,Q1,12.0,7.0,53.0,35.0,33.0,7.0,10.0,2.0,3.0,4.0,2.0,55.0,30.0,20.0,12.0,9.0,2.0,5.0
98668,1994-407,Rotterdam,Carpet,A,1994-02-21,102035,0,Jonas Bjorkman,R,SWE,21.9,101481,0,Omar Camporese,R,ITA,25.7,6-1 7-6(5),3,R32,6.0,4.0,62.0,41.0,31.0,8.0,10.0,3.0,5.0,2.0,3.0,62.0,29.0,19.0,16.0,9.0,4.0,8.0
184039,2021-0416,Rome Masters,Clay,M,2021-05-10,106234,0,Aslan Karatsev,R,RUS,27.6,106421,3.0,Daniil Medvedev,R,RUS,25.2,6-2 6-4,3,R32,1.0,0.0,50.0,29.0,26.0,13.0,9.0,1.0,1.0,5.0,1.0,58.0,38.0,23.0,12.0,9.0,3.0,6.0
157733,2011-422,Cincinnati Masters,Hard,M,2011-08-14,104597,9.0,Nicolas Almagro,R,ESP,25.9,103333,0,Ivo Karlovic,R,CRO,32.4,6-3 5-7 7-6(2),3,R32,16.0,5.0,87.0,52.0,45.0,23.0,16.0,0.0,1.0,21.0,4.0,104.0,69.0,55.0,13.0,17.0,6.0,8.0